version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shortlink-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shortlink-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postamat_user -d postamat_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: shortlink
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=shortlink_project.settings
      - DB_NAME=shortlink-db
      - DB_USER=postgres
      - DB_PASSWORD=1234
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy

volumes:
  postgres_data:
